name: Release

on:
    push:
        tags: ["v*"]
    workflow_dispatch:

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Build all platforms
              run: bun run build

            - name: Stage executables
              run: |
                  tag="${{ github.ref_name }}"
                  mkdir -p dist-release
                  cp "dist/windows/adb-autoconnect.exe" "dist-release/adb-autoconnect-$tag-windows.exe"
                  cp "dist/macos/adb-autoconnect" "dist-release/adb-autoconnect-$tag-macos"
                  cp "dist/linux/adb-autoconnect" "dist-release/adb-autoconnect-$tag-linux"

            - name: Create GitHub Release
              if: startsWith(github.ref, 'refs/tags/')
              uses: softprops/action-gh-release@v2
              with:
                  files: dist-release/*
                  generate_release_notes: true
